apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-get-deployment
  labels:
    app: ip-get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-get
  template:
    metadata:
      labels:
        app: ip-get
    spec:
      containers:
      - name: ip-get
        image: registry.cn-beijing.aliyuncs.com/yinliao/java-ip-get:0.1
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: www
            mountPath: /opt
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: nfs-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-static
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ip-get-service
spec:
  selector:
    app: ip-get
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
